spring:
  config:
    activate:
      on-profile: default
  datasource:
    driver-class-name: org.postgresql.Driver
    username: koorung
    password: test1234
    url: jdbc:postgresql://database-test1.c98c6uco009k.ap-northeast-2.rds.amazonaws.com:5432/koomart
    hikari:
      schema: kotlin

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    # Open Session In View 옵션... 기본값이 true임, false로 설정하자
    open-in-view: false

---

spring:
  config:
    activate:
      on-profile: test

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false